_locale : en-US # this is used to suggest a default values
locale : en-US # this is used to suggest a default values
_entity_category: Pacificorp #normally will be SystemGeneral
_prjprefix: PC #useful to compute process paths or entities relative ids
